# dbt_project.yml
name: 'brabble_dbt'
version: '1.0.0'
profile: 'brabble_dbt'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets: ["target","dbt_packages"]


models:
  brabble_dbt:
    +materialized: view